import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

// Root reserved segments that should NOT be rewritten to /[site]/[segment] on subdomains
const RESERVED_ROOT_PATHS = new Set([
  'login',
  'register',
  'forgot-password',
  'reset-password',
  'verify-email',
  'auth',
  'api',
  '_next',
  'favicon.ico',
  'robots.txt',
  'sitemap.xml',
  'ads.txt',
  'manifest.webmanifest',
])

function extractSubdomain(hostname: string): string {
  if (!hostname) return ''
  const isLocalhost = hostname.includes('localhost') || hostname.includes('127.0.0.1')

  if (isLocalhost) {
    // e.g. jombang.localhost:3000 -> parts = ['jombang', 'localhost:3000']
    const parts = hostname.split('.')
    if (parts.length > 1 && !parts[0].includes(':') && parts[0] !== 'localhost') {
      return parts[0].toLowerCase()
    }
  } else {
    // e.g. jombang.beritakarya.co -> parts = ['jombang', 'beritakarya', 'co']
    const parts = hostname.split('.')
    if (parts.length > 2) {
      const sub = parts[0].toLowerCase()
      if (sub !== 'www' && sub !== 'media') {
        return sub
      }
    }
  }
  return ''
}

export function middleware(req: NextRequest) {
  const url = req.nextUrl.clone()
  const pathname = url.pathname
  const hostname = req.headers.get('host') || ''

  // 1. Block placeholder query strings that leaked from SearchAction templates (e.g. ?q={search_term_string})
  const rawQuery = req.nextUrl.search
  if (rawQuery.includes('{') || rawQuery.includes('}')) {
    return new NextResponse('Not Found', { status: 404 })
  }

  // 2. Reject URLs with special character garbage segments (e.g. /&, /$, /%26, /%24)
  const decodedPath = decodeURIComponent(pathname)
  if (/^(\/&|\/\$|\/\*|\/\+)/.test(decodedPath) || /[^a-zA-Z0-9\-./_]/.test(pathname)) {
    const firstSegment = decodedPath.split('/').filter(Boolean)[0] || ''
    if (/[^a-zA-Z0-9-.]/.test(firstSegment)) {
      return new NextResponse('Not Found', { status: 404 })
    }
  }

  // 2b. Redirect any nested or non-root manifest requests to canonical root manifest
  if (pathname.endsWith('manifest.webmanifest') && pathname !== '/manifest.webmanifest') {
    return NextResponse.redirect(new URL('/manifest.webmanifest', req.url), 301)
  }

  const subdomain = extractSubdomain(hostname)
  const isSubdomain = Boolean(subdomain && subdomain !== 'pusat' && subdomain !== 'www')
  const siteId = isSubdomain ? subdomain : 'pusat'

  const pathSegments = pathname.split('/').filter(Boolean)
  const firstSegment = pathSegments[0]?.toLowerCase()

  // 3. Redirect known legacy root paths to proper canonical URLs (only when not on subdomain)
  if (!isSubdomain) {
    const ROOT_REDIRECTS: Record<string, string> = {
      privacy: '/pusat/kebijakan-privasi',
      terms: '/pusat/p/terms',
      cookies: '/pusat/cookies',
      bantuan: '/pusat/p/about',
      arsip: '/',
    }
    if (firstSegment && ROOT_REDIRECTS[firstSegment]) {
      return NextResponse.redirect(new URL(ROOT_REDIRECTS[firstSegment], req.url), 301)
    }

    // 3b. On the main domain, content routes only exist under /pusat/* because the
    // Next.js route tree is /[site]/artikel/[slug] etc. URLs shared/copied without
    // the /pusat prefix (e.g. beritakarya.co/artikel/xyz from old share links or
    // old sitemaps) would 404 — 301 them to the canonical /pusat/* path so the
    // link equity is reclaimed.
    if (firstSegment && ['artikel', 'penulis', 'p'].includes(firstSegment)) {
      return NextResponse.redirect(new URL(`/pusat${pathname}`, req.url), 301)
    }
  }

  // 4. Redirect auth pages with ?next= query parameters to clean canonical auth pages for bots
  if ((firstSegment === 'login' || firstSegment === 'register') && url.searchParams.has('next')) {
    const cleanUrl = new URL(`/${firstSegment}`, req.url)
    return NextResponse.redirect(cleanUrl, 301)
  }

  // 5. Normal root / on main domain serves the root app/page.tsx
  // (pusat site is the default homepage on beritakarya.co)
  if (!isSubdomain && pathname === '/') {
    return NextResponse.next()
  }

  // 5. Guard /dashboard routes
  const token = req.cookies.get('accessToken')?.value
  const isDashboardRoute =
    pathname === '/dashboard' ||
    pathname.startsWith('/dashboard/') ||
    /^\/[a-zA-Z0-9-]+\/dashboard(?:\/|$)/.test(pathname)

  if (isDashboardRoute && !token) {
    const loginUrl = new URL('/login', req.url)
    return NextResponse.redirect(loginUrl)
  }

  // 6. Subdomain Multi-Tenant Routing
  // On subdomains (e.g. jombang.beritakarya.co):
  // - '/' rewrites to '/jombang'
  // - '/artikel/xyz' rewrites to '/jombang/artikel/xyz'
  // - '/penulis/abc' rewrites to '/jombang/penulis/abc'
  // - '/cookies' rewrites to '/jombang/cookies'
  // - Reserved paths (login, register, api, etc.) are NOT rewritten
  if (isSubdomain) {
    // 6a. Redirect legacy /pusat/* or redundant /{subdomain}/* paths on subdomains to the clean canonical path.
    // These URLs were generated by old sitemap/metadata code or crawler assumptions:
    //   jombang.beritakarya.co/pusat/artikel/xxx → jombang.beritakarya.co/artikel/xxx
    //   jombang.beritakarya.co/jombang/artikel/xxx → jombang.beritakarya.co/artikel/xxx
    //   jombang.beritakarya.co/jombang → jombang.beritakarya.co/
    //   jombang.beritakarya.co/pusat/p/terms     → jombang.beritakarya.co/p/terms
    // The 301 redirect reclaims any link equity Google assigned to the old URL.
    if (firstSegment === 'pusat' || firstSegment === subdomain) {
      const withoutPrefix = pathname.replace(new RegExp(`^\\/${firstSegment}`), '') || '/'
      const redirectUrl = new URL(withoutPrefix, req.url)
      return NextResponse.redirect(redirectUrl, 301)
    }

    // 6b. General rewrite: prepend /{subdomain} so Next.js routes to the correct [site] segment
    if (!RESERVED_ROOT_PATHS.has(firstSegment || '') && firstSegment !== subdomain) {
      url.pathname = `/${subdomain}${pathname}`
      const response = NextResponse.rewrite(url)
      response.headers.set('x-site-id', subdomain)
      response.cookies.set('siteId', subdomain, {
        httpOnly: false,
        sameSite: 'lax',
        maxAge: 60 * 60 * 24,
      })
      return response
    }
  }

  const requestHeaders = new Headers(req.headers)
  requestHeaders.set('x-site-id', siteId)

  const res = NextResponse.next({
    request: {
      headers: requestHeaders,
    },
  })
  res.headers.set('x-site-id', siteId)
  res.cookies.set('siteId', siteId, {
    httpOnly: false,
    sameSite: 'lax',
    maxAge: 60 * 60 * 24,
  })

  return res
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico|api|robots.txt|sitemap.xml|ads.txt).*)'],
}
