export { TemplateA } from './TemplateA'
export { TemplateB } from './TemplateB'
export { TemplateC } from './TemplateC'
export { TemplateD } from './TemplateD'
export { TemplateE } from './TemplateE'
export { TemplateF } from './TemplateF'
export type { TemplateProps } from './types'
